/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#20201f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353535",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c4c7c7",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#8e9192",
        "outline-variant": "#444748",
        "surface-tint": "#c9c6c5",
        primary: "#c9c6c5",
        "on-primary": "#313030",
        "primary-container": "#0a0a0a",
        "on-primary-container": "#7b7979",
        "inverse-primary": "#5f5e5e",
        secondary: "#a2e7ff",
        "on-secondary": "#003642",
        "secondary-container": "#00d2fd",
        "on-secondary-container": "#005669",
        tertiary: "#edb1ff",
        "on-tertiary": "#520070",
        "tertiary-container": "#170023",
        "on-tertiary-container": "#a659c4",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c9c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#b4ebff",
        "secondary-fixed-dim": "#3cd7ff",
        "on-secondary-fixed": "#001f27",
        "on-secondary-fixed-variant": "#004e5f",
        "tertiary-fixed": "#f9d8ff",
        "tertiary-fixed-dim": "#edb1ff",
        "on-tertiary-fixed": "#320046",
        "on-tertiary-fixed-variant": "#6e208c",
        background: "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#353535",
        "neon-blue": "#00d4ff",
        "electric-purple": "#9d50bb",
        "brand-blue": "#00d4ff",
        "brand-purple": "#9d50bb",
        obsidian: {
          bg: "#131313",
          surface: "#20201f",
          card: "#2a2a2a",
          text: "#e5e2e1",
          muted: "#c4c7c7",
          outline: "#444748",
          neonBlue: "#00d2fd",
          neonPurple: "#edb1ff",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "800" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" },
        ],
        "code-sm": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" },
        ],
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      boxShadow: {
        glass: "0 0 0 1px rgba(255,255,255,0.1), 0 20px 40px rgba(0,0,0,0.35)",
        "neon-blue": "0 0 18px rgba(0, 210, 253, 0.45)",
        "neon-purple": "0 0 18px rgba(237, 177, 255, 0.35)",
      },
      maxWidth: {
        container: "1280px",
      },
      spacing: {
        base: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "section-gap": "120px",
        section: "7.5rem",
        stack: "1.5rem",
      },
      backgroundImage: {
        "vibrant-accent":
          "linear-gradient(135deg, rgba(0,210,253,0.22), rgba(237,177,255,0.18))",
      },
    },
  },
  plugins: [],
};
